### PR TITLE
created a new component that shows data on the BE

### PR DESCRIPTION
**Pull request by scottschindler**
# Description
Created a new functional component using Hooks that used an axios request to call data in our backend

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [x ] Test A
- [ ] Test B

# Checklist

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by tjforeman — CHANGES_REQUESTED** [review]
Looking good so far, way to use those hooks!!! we're going to have to mess with two things on sunday. 1 The build is failing, we will have to play around with that. 2 we need to make that URL dynamic, so it knows which url to hit based on it's environment. This is a really good start though.

**Comment by scottschindler** [comment]
@tjforeman Are we able to push this through now?

**Comment by ErnestoPena** [comment]
Resolve the file conflicts

**Comment by ErnestoPena** [comment]
Fixed the conflicts

**Pull request merged**
